### ISSUE TITLE
"Registration did not succeeed"

### ISSUE THREAD

**Issue by xitovx** [Grashjs/cmms#8]
All containers appear to be running fine and I can access the frontend, but when I try to register, it always results in a "Registration did not succeed" error.  no visible errors in any of the logs that I can find.

**Comment by iib0011** [comment]
Can you pls show me the browser network error

**Comment by xitovx** [comment]
![Image](https://github.com/user-attachments/assets/b66cbfe0-9bc5-41db-b6a8-bc319dda35a8)

**Comment by iib0011** [comment]
[Pls do this](https://developer.chrome.com/docs/devtools/network?hl=en#open) and show me the error

**Comment by xitovx** [comment]
![Image](https://github.com/user-attachments/assets/050eb65f-9435-4453-888e-1caf5e035008)

Okay, looks like maybe I have something misconfigured in the docker compose file.  I'm using unraid and didn't change very much in the compose file to begin with, but maybe I need to modify it more.  I got rid of the host port conflicts, but perhaps there's another conflict I'm missing?

**Comment by iib0011** [comment]
What is the url it tries to fetch? Can you click on the request?

**Comment by xitovx** [comment]
![Image](https://github.com/user-attachments/assets/4b8e075f-8923-4cd2-af75-8ac1faf70f60)

Ok, so after seeing the URL, i understand why it failed.  port 8080 is not available on this machine, so I remapped it to 8088.  I went back and modified the related entries in the .env file, and made sure everything in the compose file matched properly as well.  I've modified both files to include the correct port, but it is still requesting at the old port (8080) address.  Is this hardcoded somewhere?

I also now have an error in the API log that seems to match port 8080

**Comment by xitovx** [comment]
![Image](https://github.com/user-attachments/assets/f52dba11-295b-4833-8859-bd5ca243738c)

sorry, here is the API error log

**Comment by iib0011** [comment]
Once you change public api url or any env starting with react you need to rebuild using

`docker-compose up -d --no-deps --build`

**Comment by xitovx** [comment]
Okay, that must be what I'm missing, then.  I have been composing up and composing down with each change, but through the Unraid interface which seems to be just reusing the existing images instead of rebuilding them.  I will delete them and build from scratch to see if that resolves it.

**Comment by xitovx** [comment]
Ok, it seems to be pointing to the right address now, but I still get "Registration didn't succeed" but apparently for a different reason than before.

![Image](https://github.com/user-attachments/assets/6e5375ed-8961-42d7-9f26-02c84504e507)

**Comment by iib0011** [comment]
can you look at the request payload? Maybe it is "Email is already in use"

**Comment by xitovx** [comment]
Oh, that's it.  Just, unfortunately my password isn't working.  I must have mistyped it at some point.  I'll try to restart from scratch with this new configuration.  Looks like it should fix it.

**Comment by iib0011** [comment]
Tell me if that worked so I can close the issue

**Comment by xitovx** [comment]
![Image](https://github.com/user-attachments/assets/8dff0089-df68-478d-839e-0bd742941ac1)

Ok, that worked, except I assume I still get the failure message because it fails to send the activation email (not configured).  Since I can't activate the account, I'm unable to log in afterward.  I get "Invalid Credentials".  Is gmail the only option for that?  I can try the app password again if so, then just disable it after I've activated the account, I hope.  I have smtp options I could use but would really like to avoid gmail long term.

**Comment by xitovx** [comment]
Ok, confirmed functionally resolved.  I did get the email now, I was able to activate and then log in.  But I still get the "Registration didn't succeed error"

**Comment by iib0011** [comment]
What is the error in network tab

**Comment by xitovx** [comment]
This is the only error I can find in the Network tab.  Otherwise, it's just the red message in the webgui

![Image](https://github.com/user-attachments/assets/0d7e2891-0b3d-496a-ae06-3aa3906e9cc0)

**Comment by iib0011** [comment]
Show me the console error if there is no network error on signup

**Comment by xitovx** [comment]
![Image](https://github.com/user-attachments/assets/11edc41e-8ae9-4600-b47e-8d4e8daaaf1c)

I couldn't find anything in the docs about MUI license.  Not sure what that is.

**Comment by iib0011** [comment]
Do you have the latest version of the code. Git pull if possible. Then recreate containers 
You will see REACT_APP_MUI_X_LICENSE as env in the docs. It is needed for the tables.

To fix your error update PUBLIC_FRONT_URL

**Comment by xitovx** [comment]
I have the REACT_APP_MUI_X_LICENSE in env already, but couldn't seem to find a way to get a password for the free license at the link it provides, and I don't think the $15 Pro plan is worth it for my microscopic use case, just trying to get maintenance done around the home.  Either way, thanks for your support.  Maybe I just need to keep hunting for the right cmms for me.

**Comment by iib0011** [comment]
If you dont mind the MUI filigrane, you can still use the application. No need to buy the license. Did updating `PUBLIC_FRONT_URL` work for you?

**Comment by iib0011** [comment]
By the way i will remove the filigrane for the tables that dont need pro

**Comment by xitovx** [comment]
I had already changed PUBLIC_FRONT_URL to the correct address, and the frontend is accessible if I copy and paste that address.  Not clear to me what is configured wrong about it.  The filigrane might not be an issue- will see.

**Comment by iib0011** [comment]
Did you have FRONT_URL or PUBLIC_FRONT_URL before, Maybe you are using an old version. If so pls git pull and recreate

**Comment by huytn95** [comment]
I have the same issues, my case is as follows:

I pulled the latest version yesterday on my workstation, changed the PUBLIC_FONT_URL and PUBLIC_API_URL in the .env file to my public IP, ran the command "docker compose up -d --no-deps --build", and started the application (still on my workstaion). The frontend is accessible via the public IP, but when i log in (this account was created when i ran the app with the old version), i get the error "Wrong credentials provided". Then, i tried accessing via the localhost:3000 link instead of the public IP, and i was able to log in successfully (i don't understand why the account created in the old version could log in, even though i had deleted all docker images before pulling the new version).
Additionally, when i tried to create a new account (still on localhost), i encountered the " 'Registration did not succeed' error, as mentioned above. 
I'm not a programming expert, but I suspect the issue lies in the file frontend/src/config.ts".
Do you have any ideas about this?

**Comment by iib0011** [comment]
You were right. There was an issue. I just fixed it. Pls try again with the latest version and `docker-compose up -d --no-deps --build`

**Comment by huytn95** [comment]
I have successfully logged in via public ip but it seems the registration function is still failing.

Where is the user data stored? i tried to connect to postgres using DBeaver and i can't find any tables there.

**Comment by iib0011** [comment]
I just fixed it. If it is no in localhost, it will try to send email on signup. Make sure to configure SMTP

**Comment by huytn95** [comment]
Thank for your support @iib0011, it works perfectly now. I will continue to test other functions and report bugs (if any).

**Comment by iib0011** [comment]
@xitovx is your issue solved?

**Comment by xitovx** [comment]
Hi sorry I was tied up with a pet emergency.   I just updated and I get some new errors in the console, but everything seems to be working so far.  I will continue to test things and report back any issues.

**Comment by iib0011** [comment]
Great
