### ISSUE TITLE
Unable to download template for data import

### ISSUE THREAD

**Issue by huytn95** [Grashjs/cmms#9]
I am unable to download the template file (work orders, assets, locations, parts, meters) to import data.
Please check.

![Image](https://github.com/user-attachments/assets/20ac60b4-afc5-4695-abf5-81020569073d)

**Comment by iib0011** [comment]
Thanks for letting me know. I just fixed it

**Comment by huytn95** [comment]
Hi @iib0011, the export function has the same issue as the import function, please check.

**Comment by iib0011** [comment]
@huytn95 It is fixed, pls check

**Comment by huytn95** [comment]
> [@huytn95](https://github.com/huytn95) It is fixed, pls check

The issue is still not fixed.

![Image](https://github.com/user-attachments/assets/3c36110e-99bb-400e-a912-aa9a82202f25)

**Comment by iib0011** [comment]
Pls check and tell me

**Comment by huytn95** [comment]
> Pls check and tell me. Git pull and
> 
> docker compose up -d --no-deps --build api

It works. Thanks @iib0011
